name: provable_claims
run-name: ${{ github.actor }} is running provable_claims

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Job triggered by a ${{ github.event_name }} event @ ${{ github.repository }}/${{ github.ref }}"
            - name: Clone ProvableClaims
              uses: actions/checkout@v3
              with:
                  name: CapyRobot/ProvableClaims
                  path: "pc"
            - name: Clone project
              uses: actions/checkout@v3
              with:
                  path: "project"
            - name: Set up Python 3.9
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r pc/requirements.txt; fi
            - name: Run ProvableClaims
              run: |
                  cd ./project
                  python ../pc/provable_claims/provable_claims.py
